another test

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,11 +1,12 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npm run build
-git add ./app
-if git commit -m "build app" ; then
-    echo "app built"
-    git push --no-verify
-    echo "push done"
-    exit 127
-fi
+# npm run build
+# git add ./app
+# if git commit -m "build app" ; then
+#     echo "app built"
+#     git push --no-verify
+#     echo "push done"
+#     echo "hook will trigger an error even if everything is fine"
+#     exit 1
+# fi
